<?php
function copyright_block_block_info() {
  // This example comes from node.module.
  $blocks['copyright_block'] = array(
    'info' => t('Copyright information'), 
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

function copyright_block_block_configure($delta = '') {
  $form = array();
  if ($delta == 'copyright_block') {
    $form['copyright_block_name'] = array(
      '#type' => 'textfield',
      '#title' => t('Copyright holder'),
      '#size' => 30,
      '#description' => t('Leave this field empty to use the site name as copyright holder.'),
      '#default_value' => variable_get('site_name', ''),
    );
    $form['copyright_block_year'] = array(
      '#type' => 'textfield',
      '#title' => t('Initial copyright year'),
      '#size' => 4,
      '#description' => t('The first year in the span of years covered by copyright. Set this to the current year to display the current year only, instead of a range of years.'),
      '#default_value' => variable_get('copyright_block_year',  date("Y", time ())),
    );
	  $form['title'] = array(
      '#type' => 'textfield',
      '#title' => t('Block Title'),
      '#size' => 30,
      '#description' => t('Override the default title for the block. Use <none> to display no title, or leave blank to use the default block title.'),
      '#default_value' => t(''),
    );
  }
  return $form;
}
function copyright_block_block_save($delta = '', $edit = array()) {
  if ($delta == 'copyright_block') {
    variable_set('copyright_block_name', $edit['copyright_block_name'] ? check_plain($edit['copyright_block_name']) : $sitename);
    variable_set('copyright_block_year', check_plain($edit['copyright_block_year']));
  }
}


function copyright_block_block_view($delta = '') {
	if ($delta == 'copyright_block') {
		$sitename = variable_get('copyright_block_name',  variable_get('site_name', ''));
		$default_name = variable_get('copyright_block_name', $sitename) == $sitename ? '' : variable_get('copyright_block_name', '');
		$block = array();
		$block['subject'] = t('');
		$block['content'] = copyright_block_contents($sitename);
		return $block;
	}
}

function copyright_block_contents($sitename) {
	$output = '<span class="copyright">&copy; ';
	$copy_start = variable_get('copyright_block_year',  date("Y", time ()));
	$this_year = date("Y", time ());

	$output .= ($copy_start == $this_year ? $this_year : $copy_start . ' - ' . $this_year) . ', '. $sitename;
	$output .= '</span>';
  return $output;
}